# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prof_pictures/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_caption', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
