# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181012_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Project',
        ),
    ]
